name: CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: Create .env
      run: cp docker/example.env docker/.env

    - name: Install project dependencies
      run: PIPENV_PIPFILE=config/Pipfile pipenv install --dev

    - name: Run unit-tests
      run: make unit-test

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: Create .env
      run: cp docker/example.env docker/.env

    - name: Install project dependencies
      run: PIPENV_PIPFILE=config/Pipfile pipenv install --dev

    - name: Docker up broker
      run: make up-broker

    - name: Docker up DronePort
      run: make -C systems/drone_port docker-up-no-broker

    - name: Docker up GCS
      run: make -C systems/gcs docker-up-no-broker

    - name: Run broker integration-tests
      run: make integration-test-broker-no-up

    - name: Run DronePort integration-tests
      run: make integration-test-drone-port-no-up

    - name: Run GCS integration-tests
      run: make integration-test-gcs-no-up

    - name: Dump broker logs
      if: always()
      run: |
        docker logs kafka || true
        docker logs mosquitto || true
        docker logs fabric-proxy || true
        docker logs ledger-gateway || true

    - name: Dump GCS logs
      if: always()
      run: |
        docker logs gcs-mission_store-1 || true
        docker logs gcs-drone_store-1 || true
        docker logs gcs-mission_converter-1 || true
        docker logs gcs-orchestrator-1 || true
        docker logs gcs-path_planner-1 || true
        docker logs gcs-drone_manager-1 || true

    - name: Dump DronePort logs
      if: always()
      run: |
        docker logs drone-port-state_store-1 || true
        docker logs drone-port-port_manager-1 || true
        docker logs drone-port-drone_registry-1 || true
        docker logs drone-port-charging_manager-1 || true
        docker logs drone-port-drone_manager-1 || true
        docker logs drone-port-orchestrator-1 || true

    - name: Docker down
      if: always()
      run: |
        make down-drone-port
        make down-gcs
        make down-broker
