name: CI

on:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make

    - name: Create .env
      run: cp docker/example.env docker/.env

    - name: Initialization
      run: make init

    - name: Run unit-tests
      run: make unit-test

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y make

    - name: Create .env
      run: cp docker/example.env docker/.env

    - name: Initialization
      run: make init

    - name: Docker up
      run: |
        make docker-up
        make dummy-system-up
        make gcs-system-up
        sleep 60

    - name: Run integration-tests
      run: make integration-test-run

    - name: Dump logs for each container
      if: always()
      run: |
        docker logs drones-mission_store-1 || true
        docker logs drones-drone_store-1 || true
        docker logs drones-mission_converter-1 || true
        docker logs drones-orchestrator-1 || true
        docker logs drones-path_planner-1 || true
        docker logs drones-drone_manager-1 || true

    - name: Docker down
      if: always()
      run: |
        make gcs-system-down
        make dummy-system-down
        make docker-down
